.PHONY: default, install, uninstall
config_location = /etc/fireman

default:
	# We scripting.

install:
	if test -e /etc/fireman; then
		if test -d /etc/fireman; then
			:
		else
			echo "/etc/
	if test -d /etc/fireman; then
		


	cp core/master.conf /et	
